# Generated by Django 5.1.1 on 2024-10-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_created_at_event_status_pass_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='qrcode',
            field=models.ImageField(upload_to='images/qrcodes/'),
        ),
    ]
